import type { Chapter } from '../../core/content';
import { ARRIVAL_DAY, lightDelayMinutes } from '../../core/orbit';
import { has, hasFlag } from '../../core/state';
import { crew, fmtMin, L } from '../helpers';

const sheltered = (s: Parameters<typeof has>[0]) => has(s, 'water_wall');

export const ch2: Chapter = {
  id: 2,
  title: '第二章 · 深空',
  subtitle: '地火转移轨道 · 第 1–259 天',
  teach: '风险判断：你手里的信息，永远是旧的',
  march: '跋涉：万水千山，靠的是彼此。',
  scene: 'cruise',
  beats: [
    {
      id: 'routine',
      title: '巡航作息',
      scene: 'cruise',
      lines: [
        L('sys', '任务第 3 天 · 距地球 120 万公里'),
        L('amara', '失重第三天，我终于不会把勺子弄丢了。'),
        L('andrei', '睡眠数据不太好。凛昨晚只睡了四个小时——她一直在看火星的照片。'),
        L('rin', '我在做功课！'),
        L('qin', '巡航很长。怎么安排他们的作息，会一直影响到火星上。'),
      ],
      decision: {
        kind: 'choice',
        prompt: '巡航期的作息怎么安排？',
        options: [
          { id: 'science', label: '科研优先：舱内实验排满', detail: '科研 +8 · 士气 −6', effect: { science: 8, crew: { all: { morale: -6 } } },
            lines: [L('rin', '太好了，微重力晶体生长实验可以多做三轮！'), L('andrei', '……我会盯着他们的睡眠。')] },
          { id: 'balance', label: '均衡：实验与休息交替', detail: '科研 +4', effect: { science: 4 },
            lines: [L('lin', '收到，按标准作息执行。')] },
          { id: 'rest', label: '休整优先：多留自由时间', detail: '士气 +6', effect: { crew: { all: { morale: 6 } } },
            lines: [L('amara', '那我可以教大家玩我老家的棋了！'), L('zhou', '……希望他们到火星时还记得自己是来干什么的。')] },
        ],
      },
      archive: ['mars500'],
      days: 50,
    },
    {
      id: 'spe',
      title: '太阳风暴',
      scene: 'spe',
      key: true,
      lines: (s) => [
        L('sys', '太阳动力学观测：X2.8 级耀斑，日冕物质抛射方向朝向飞船。', { tone: 'alert' }),
        L('capcom', `现在的单程延迟是 ${fmtMin(lightDelayMinutes(s.day))}。我们看到耀斑的时候，第一批高能质子可能已经在路上了。`),
        L('zhou', '舱内正在做一组关键实验，中断就前功尽弃。能不能等确认了再避险？'),
        sheltered(s)
          ? L('andrei', '水墙避难舱随时可以进人。')
          : L('andrei', '我们没有水墙。只能把储水袋堆在睡眠舱四周，临时凑一个避难所。', { tone: 'alert' }),
        L('qin', '看看那个风险区间。那就是“信息是旧的”的样子。'),
      ],
      decision: {
        kind: 'choice',
        prompt: '太阳粒子事件预警：怎么办？',
        options: [
          { id: 'shelter', label: '立即全员避险', basis: '好奇号 RAD 实测：屏蔽厚度显著影响太阳粒子事件的剂量。',
            detail: (s) => (sheltered(s) ? '科研 −4 · 剂量约 +15 mSv' : '科研 −4 · 剂量约 +45 mSv（没有水墙）'),
            effect: (s) => ({ science: -4, crew: { all: { dose: sheltered(s) ? 15 : 45 }, andrei: { dose: 40 } }, flags: ['andrei_symptom'] }),
            lines: [L('lin', '全员进避难舱。沃尔科夫，你最后一个进来。'), L('andrei', '实验样本要先固定好……我马上来。')] },
          { id: 'wait', label: '等待确认，保住实验', basis: '最快的高能粒子在耀发后数十分钟内即可抵达。',
            detail: '保住实验（科研 +6）；若粒子先到，剂量大增',
            effect: { flags: ['andrei_symptom'] },
            risk: { base: 0.55, label: '粒子先于确认抵达', mod: (s) => (has(s, 'sensors') ? -0.25 : 0),
              fail: (s) => ({ crew: { all: { dose: sheltered(s) ? 90 : 150 }, andrei: { dose: 80 } } }),
              failLines: [L('sys', '质子通量骤升！剂量计报警。', { tone: 'alert' }), L('andrei', '大家先进去，我把样本柜锁上——', { tone: 'alert' }), L('zhou', '……是我判断错了。')],
              okLines: [L('sys', '确认：本次事件主峰偏离飞船方向，剂量轻微上升。', { tone: 'calm' }), L('zhou', '实验保住了。'), L('andrei', '我顺手把样本柜加固了一下，花了点时间。')],
            },
            lines: [L('lin', '收到，继续实验，保持警戒。')] },
          { id: 'delegate', label: '授权指令长现场判断',
            detail: '林照凭现场读数决定（信任 +6）；结果取决于他的判断',
            effect: { flags: ['andrei_symptom', 'qin_delegate_spe'], crew: { all: { trust: 6 } } },
            risk: { base: 0.3, label: '现场判断失误', mod: (s) => -(crew(s, 'lin').trust - 60) / 200,
              fail: (s) => ({ crew: { all: { dose: sheltered(s) ? 60 : 100 }, andrei: { dose: 60 } } }),
              failLines: [L('lin', '读数涨得太快了……我晚了两分钟下令。', { tone: 'alert' })],
              okLines: [L('lin', '剂量计一跳，我就让大家进去了。实验做了一半，值得。'), L('qin', '……嗯。')],
            },
            lines: [L('lin', '收到。我们看着剂量计自己决定。')] },
        ],
      },
      archive: ['spe', 'rad'],
      days: 60,
    },
    {
      id: 'water',
      title: '水回收故障',
      scene: 'cruise',
      lines: [
        L('amara', '坏消息：水回收装置的蒸馏组件结垢了，回收率从 98% 掉到 85%。', { tone: 'alert' }),
        L('amara', '好消息：我有个主意。用备用加热带改一条旁路，应该能撑住——大概吧。'),
      ],
      decision: {
        kind: 'choice',
        prompt: '水回收装置故障，怎么修？',
        options: [
          { id: 'spare', label: '更换备件', detail: '消耗 1 份备件，稳妥修复',
            requires: (s) => s.spares > 0, lockedReason: '没有备件了',
            effect: { spares: -1 }, lines: [L('amara', '换上了。说实话，有点遗憾没能试试我的主意。')] },
          { id: 'improvise', label: '让阿玛拉即兴改装', detail: '不耗备件；成功则阿玛拉士气与信任提升，失败损失大量水',
            effect: { crew: { amara: { trust: 8 } } },
            risk: { base: 0.35, label: '改装失败', fail: { water: -70, crew: { amara: { morale: -10 } } },
              failLines: [L('sys', '旁路加热带过热，冷凝水外泄 40 升。', { tone: 'alert' }), L('amara', '……对不起。我会把它修好的，用正规办法。')],
              okLines: [L('amara', '回收率回到 96%！我就说能行！'), L('lin', '漂亮。')] },
            lines: [L('amara', '交给我。')] },
          { id: 'ration', label: '降低用水标准，撑到火星', detail: '水 −25 · 全员士气 −8',
            effect: { water: -25, crew: { all: { morale: -8 } } },
            lines: [L('rin', '两天洗一次头……好吧。'), L('andrei', '注意补水，脱水比你们想的危险。')] },
        ],
      },
      archive: ['eclss'],
      days: 60,
    },
    {
      id: 'psych',
      title: '第 170 天',
      scene: 'cruise',
      lines: (s) => [
        L('sys', `任务第 ${s.day} 天 · 单程延迟 ${fmtMin(lightDelayMinutes(s.day))}`),
        L('lin', '这几天舱里有点紧张。凛和阿玛拉为了实验时段吵了一架，现在谁也不理谁。'),
        L('andrei', '火星-500 的数据里，第 150 天前后也有类似的低谷。很正常——但不能不管。'),
        L('andrei', '另外……大家都想多和家里通几次话。'),
        L('qin', '你们之间的对话，现在要等十分钟才能得到回音。他们和家人之间也一样。'),
      ],
      decision: {
        kind: 'choice',
        prompt: '怎么处理乘组的情绪低谷？',
        options: [
          { id: 'family', label: '增加家庭通话带宽（挤占科研下行）', detail: '全员士气 +12 · 科研 −6',
            effect: { science: -6, crew: { all: { morale: 12, trust: 4 } } },
            lines: [L('amara', '我妈妈录了一段视频，她在教我侄子说“火星”。'), L('rin', '谢谢你。真的。')] },
          { id: 'together', label: '安排集体任务和固定作息', detail: '全员士气 +6 · 信任 +4', basis: '火星-500：固定作息与共同目标有助于维持团队状态。',
            effect: { crew: { all: { morale: 6, trust: 4 } } },
            lines: [L('lin', '我们一起做了顿“火星火锅”。凛和阿玛拉又开始说话了。')] },
          { id: 'discipline', label: '维持现状，强调纪律', detail: '科研 +4 · 全员士气 −6 · 信任 −6',
            effect: { science: 4, crew: { all: { morale: -6, trust: -6 } } },
            lines: [L('lin', '……收到。'), L('andrei', '我会尽力。')] },
        ],
      },
      days: 50,
    },
    {
      id: 'andrei_med',
      title: '医疗遥测',
      scene: 'cruise',
      when: (s) => hasFlag(s, 'andrei_symptom') && has(s, 'med'),
      enter: { flags: ['andrei_found'] },
      lines: [
        L('sys', '医疗舱血液分析仪：A. 沃尔科夫白细胞计数持续偏低（2.9×10⁹/L）。', { tone: 'alert' }),
        L('andrei', '……瞒不住了。太阳风暴那天我最后一个进舱，剂量比别人高。我不想让大家担心。'),
        L('andrei', '已经开始用药了。发现得早，问题不大。'),
      ],
      days: 0,
    },
    {
      id: 'andrei_check',
      title: '迟到的体检报告',
      scene: 'cruise',
      when: (s) => hasFlag(s, 'andrei_symptom') && !has(s, 'med'),
      lines: [
        L('sys', '提示：A. 沃尔科夫的例行血常规报告第三次延期上传。'),
        L('andrei', '最近太忙了，下周一定补上。'),
      ],
      decision: {
        kind: 'choice',
        prompt: '医生的体检报告一直没有上传……',
        options: [
          { id: 'demand', label: '要求他立即上传原始数据', detail: '一定能查清；沃尔科夫信任 −10',
            effect: { flags: ['andrei_found'], crew: { andrei: { trust: -10 } } },
            lines: [L('andrei', '……好吧。白细胞偏低。太阳风暴那天我最后一个进舱。'), L('andrei', '我本来想自己处理的。抱歉。')] },
          { id: 'ask_lin', label: '请林照私下问问他', detail: '是否问出实情，取决于林照与他的关系',
            risk: { base: 0.45, label: '没问出实情', mod: (s) => -(crew(s, 'lin').trust - 60) / 150,
              fail: { crew: { andrei: { trust: 3 } } },
              ok: { flags: ['andrei_found'] },
              failLines: [L('lin', '他说一切正常，只是太忙。我……信了。')],
              okLines: [L('lin', '我们聊了很久。他说了实话：白细胞偏低，已经在用药。'), L('andrei', '谢谢你们没有逼我。')] },
            effect: {}, lines: [L('lin', '我找个时间和他聊聊。')] },
          { id: 'respect', label: '尊重他的隐私，不追问', detail: '沃尔科夫信任 +5',
            effect: { crew: { andrei: { trust: 5 } } },
            lines: [L('andrei', '谢谢。')] },
        ],
      },
      days: 0,
    },
    {
      id: 'approach',
      title: '火星在望',
      scene: 'orbit',
      lines: (s) => [
        L('sys', `任务第 ${s.day} 天 · 距火星 40 万公里`),
        L('lin', '火星在舷窗里一天比一天大。红得……不太真实。'),
        L('rin', '我能看见水手谷了！'),
        L('qin', '再过几天就是进入、下降与着陆。整整七分钟，你什么都做不了。', { voice: 'ch2_01' }),
        L('qin', '所以，七分钟里要说的话，现在就得想好。'),
      ],
      days: (s) => Math.max(0, ARRIVAL_DAY - s.day),
    },
  ],
};
