// 科学档案：游戏中解锁，结算页展示。数值核对见 docs/SCIENCE.md
export interface ArchiveCard {
  id: string;
  title: string;
  body: string;
  game: string; // 游戏中如何简化
  source: string;
}

export const ARCHIVE: ArchiveCard[] = [
  { id: 'light_delay', title: '光速延迟',
    body: '地火距离在约 0.37–2.7 AU 之间变化，无线电信号单程需要约 3–22 分钟。地面无法“实时遥控”火星上的任何东西。',
    game: '游戏按圆轨道模型实时计算延迟，并标注在每条来自火星的消息上。',
    source: 'NASA Mars Exploration Program：Communications with Earth' },
  { id: 'hohmann', title: '霍曼转移与发射窗口',
    body: '霍曼转移是两条圆轨道之间最省燃料的椭圆转移轨道。地火之间的单程约 8.5 个月，合适的相对位置约每 26 个月出现一次。',
    game: '圆轨道近似下转移 259 天，火星停留 454 天等待返程窗口。',
    source: 'Curtis, Orbital Mechanics for Engineering Students, 第 6 章' },
  { id: 'rad', title: '深空辐射剂量',
    body: '好奇号在 2011–2012 年飞往火星途中用 RAD 探测器实测：巡航剂量率约 1.8 mSv/天，按 180 天单程计算往返约 0.66 Sv。',
    game: '巡航 1.8 mSv/天，水墙屏蔽 ×0.7；任务剂量上限取 1000 mSv。',
    source: 'Zeitlin et al., Science 340 (2013)' },
  { id: 'spe', title: '太阳粒子事件',
    body: '耀斑和日冕物质抛射会释放高能质子。最快的粒子在几十分钟内抵达，航天员需要躲进屏蔽最厚的舱段。',
    game: '巡航期随机发生，是否立刻避险取决于你对“过时信息”的判断。',
    source: 'NOAA Space Weather Prediction Center' },
  { id: 'eclss', title: '再生式生命保障',
    body: '空间站的水回收系统在 2023 年实现约 98% 的水回收率，氧气则主要由电解水产生。',
    game: '物资以“可维持天数”计量，再生系统降低了实际消耗。',
    source: 'NASA ECLSS 新闻稿（2023 年 6 月）' },
  { id: 'mars500', title: '火星-500',
    body: '2010–2011 年，六名志愿者在莫斯科的密闭舱里模拟了 520 天火星往返任务，研究长期隔离对睡眠、情绪和协作的影响。',
    game: '巡航期士气缓慢下降，作息与沟通决策会影响团队状态。',
    source: 'Basner et al., PNAS 110 (2013)' },
  { id: 'edl', title: '恐怖七分钟',
    body: '探测器以约 5.8 km/s 进入火星大气，经过气动减速、降落伞、反推着陆，全程约 7 分钟，而信号单程延迟超过 7 分钟，全程只能自主执行。',
    game: '着陆前写入预案卡，盲区内的故障由预案或乘组自主处置。',
    source: 'NASA JPL：Curiosity / Perseverance EDL' },
  { id: 'dust2018', title: '2018 年全球沙尘暴',
    body: '2018 年 6 月，一场全球性沙尘暴使大气光学厚度 τ 超过 10，机遇号的太阳能输出骤降，最终失联，任务于 2019 年结束。',
    game: '沙尘暴把 τ 推高到 9，太阳能输出跌到原来的约 7%，核电不受影响。',
    source: 'NASA JPL：Opportunity mission updates, 2018' },
  { id: 'solar_mars', title: '火星上的太阳能',
    body: '火星距太阳约 1.52 AU，轨道处太阳辐照约 590 W/m²，约为地球的 43%，高纬度和沙尘还会进一步降低发电量。',
    game: '太阳能输出 = 名义功率 × 纬度系数 × 沙尘衰减。',
    source: 'NASA Mars Fact Sheet' },
  { id: 'kilopower', title: '千瓦级裂变电源',
    body: 'NASA 与美国能源部在 2018 年完成 KRUSTY 地面试验，验证了 1–10 kWe 级小型裂变电源，可在沙尘暴和极夜中稳定供电。',
    game: '裂变电源恒定提供 10 kW。',
    source: 'NASA Glenn：Kilopower / KRUSTY (2018)' },
  { id: 'moxie', title: 'MOXIE 原位制氧',
    body: '毅力号携带的 MOXIE 在 2021–2023 年间 16 次运行，从火星大气 CO₂ 中共制取 122 克氧气，峰值约 12 克/小时。',
    game: '放大版 MOXIE-X 满功率时覆盖大部分用氧，需要 3 kW 电力。',
    source: 'Hecht et al., Science Advances (2022)；NASA 2023' },
  { id: 'ice', title: '火星浅层水冰',
    body: 'SWIM（火星地下水冰测绘）项目综合多种轨道数据，发现中纬度部分地区距地表不到 1 米处就有水冰。',
    game: '提水产量 = 设备能力 × 着陆点冰储量系数。',
    source: 'NASA JPL SWIM Project (2019–)' },
  { id: 'sabatier', title: '萨巴蒂尔反应',
    body: 'CO₂ + 4H₂ → CH₄ + 2H₂O。用火星大气和水冰就地生产甲烷/液氧推进剂，是载人火星返回方案的关键技术。',
    game: '上升器推进剂由预置工厂生产，速度取决于电力与水。',
    source: 'Zubrin, Mars Direct (1991)；NASA DRA 5.0 (2009)' },
  { id: 'conjunction', title: '日凌',
    body: '大约每 26 个月，太阳会运行到地球与火星之间，太阳等离子体干扰无线电，火星任务会暂停发送指令约两周。',
    game: '圆轨道模型下日凌发生在抵达后第 220 天左右，持续约 15 天。',
    source: 'NASA：Mars Solar Conjunction' },
  { id: 'ingenuity', title: '机智号',
    body: '机智号是第一架在其他行星上动力飞行的飞行器，2021–2024 年完成 72 次飞行，为毅力号侦察路线。',
    game: '侦察直升机降低着陆与出舱风险。',
    source: 'NASA JPL：Ingenuity Mars Helicopter' },
  { id: 'site_utopia', title: '乌托邦平原',
    body: '天问一号的祝融号火星车于 2021 年 5 月着陆在乌托邦平原南部，次表层雷达揭示了浅层多层结构。',
    game: '最平坦安全，中等冰储量。',
    source: '中国国家航天局；Li et al., Nature (2022)' },
  { id: 'site_jezero', title: '杰泽罗撞击坑',
    body: '杰泽罗坑曾是一个古湖，西侧保留着河流三角洲。毅力号正在这里采集可能保存古生命痕迹的岩芯。',
    game: '科研 ×1.5，但着陆风险最高、冰最少。',
    source: 'NASA JPL：Mars 2020 Perseverance' },
  { id: 'site_arcadia', title: '阿卡迪亚平原',
    body: '阿卡迪亚平原位于北半球中纬度，被认为是载人着陆的候选区之一，浅层水冰丰富。',
    game: '冰储量最高，但纬度高、太阳能弱。',
    source: 'Morgan et al., Nature Astronomy (2021)' },
  { id: 'sol', title: '火星日',
    body: '一个火星日（sol）约 24 小时 39 分 35 秒，比地球日长约 2.7%。火星任务团队通常按火星时间倒班。',
    game: '地表阶段同时显示任务日与火星日。',
    source: 'NASA Mars Fact Sheet' },
];

export const archiveById = (id: string) => ARCHIVE.find((a) => a.id === id);
